name: Generate Microsoft Apps NuGet Packages

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      nuGetServerUrl:
        description: NuGet server URL (leave empty to use NUGETSERVERURL variable)
        required: false
        default: ''
      nuGetToken:
        description: NuGet auth token (leave empty to use NUGETTOKEN secret)
        required: false
        default: ''
      artifactVersion:
        description: Business Central Version to generate nuget packages for
        required: true
        default: ''
      run-name:
        description: Name of the run (leave empty to use the default name)
        required: false
        default: ''

run-name: ${{ github.event.inputs.run-name != '' && github.event.inputs.run-name || github.workflow }}

concurrency:
  group: ${{ github.event.inputs.run-name != '' && github.event.inputs.run-name || github.workflow }}
  cancel-in-progress: false

jobs:
  GenerateMSAppsNuGetPackages:
    name: Generate Microsoft Apps NuGet Packages
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        country: [ "at", "au", "be", "ca", "ch", "cz", "de", "dk", "es", "fi", "fr", "gb", "in", "is", "it", "mx", "nl", "no", "nz", "ru", "se", "us", "w1" ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mask input
        shell: pwsh
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "MaskInput.ps1")

      - name: Generate MS Apps
        shell: pwsh
        env:
          artifactType: 'sandbox'
          artifactVersion: ${{ github.event.inputs.artifactVersion }}
          country: ${{ matrix.country }}
        run: |
          . (Join-Path $env:GITHUB_WORKSPACE "GenerateMSApps.ps1")
